/**
 * Differential test: this TypeScript port must reproduce the REFERENCE
 * py-fsrs implementation bit-for-bit (to float tolerance).
 *
 * Golden fixture in data/fsrs-golden.json was generated by running the real
 * `fsrs` PyPI package. Regenerate with:
 *   uv run tools/gen-fsrs-fixture.py > data/fsrs-golden.json
 */
import { describe, expect, test } from "bun:test";
import { Scheduler, newCard, type Card, type Rating } from "./fsrs";

const golden = await Bun.file(new URL("../data/fsrs-golden.json", import.meta.url)).json();
const DAY = 86_400_000;
const START = Date.parse(golden.start_iso);

// Fuzzing disabled to match the fixture; py-fsrs uses random() otherwise.
const sched = new Scheduler({ enableFuzzing: false });

describe("FSRS-6 port matches py-fsrs reference", () => {
  for (const c of golden.cases) {
    test(`case ${c.seq}`, () => {
      let card: Card = newCard(START);
      let t = START;
      c.steps.forEach((s: any, i: number) => {
        t += s.gap_days * DAY;
        card = sched.review(card, s.rating as Rating, t);
        const where = `case ${c.seq} step ${i} (rating=${s.rating}, gap=${s.gap_days}d)`;
        expect(card.stability, `${where} stability`).toBeCloseTo(s.stability, 9);
        expect(card.difficulty, `${where} difficulty`).toBeCloseTo(s.difficulty, 9);
        expect(card.state, `${where} state`).toBe(s.state);
        expect(card.step, `${where} step`).toBe(s.step);
        expect(card.due - t, `${where} interval`).toBe(s.due_offset_ms);
      });
    });
  }
});

describe("FSRS invariants", () => {
  test("21 parameters required", () => {
    expect(() => new Scheduler({ parameters: [1, 2, 3] })).toThrow();
  });

  test("review does not mutate the input card", () => {
    const a = newCard(START);
    const snapshot = JSON.stringify(a);
    sched.review(a, 3, START);
    expect(JSON.stringify(a)).toBe(snapshot);
  });

  test("retrievability decays monotonically and stays in (0,1]", () => {
    let card = sched.review(newCard(START), 3, START);
    card = sched.review(card, 3, START + DAY); // push into review state
    let prev = Infinity;
    for (let d = 0; d < 400; d += 7) {
      const r = sched.retrievability(card, card.lastReview! + d * DAY);
      expect(r).toBeGreaterThan(0);
      expect(r).toBeLessThanOrEqual(1);
      expect(r).toBeLessThanOrEqual(prev + 1e-12);
      prev = r;
    }
  });

  test("interval at desired retention 0.9 approximates stability", () => {
    // FSRS property: when desiredRetention == 0.9, interval ≈ stability.
    const s = new Scheduler({ enableFuzzing: false, desiredRetention: 0.9 });
    let card = newCard(START);
    let t = START;
    for (const [rating, gap] of [[3, 0], [3, 1], [3, 5], [3, 20]] as const) {
      t += gap * DAY;
      card = s.review(card, rating as Rating, t);
    }
    const intervalDays = (card.due - t) / DAY;
    expect(intervalDays).toBeCloseTo(Math.round(card.stability!), 0);
  });

  test("Again after a long streak reduces stability", () => {
    const s = new Scheduler({ enableFuzzing: false });
    let card = newCard(START);
    let t = START;
    for (const gap of [0, 1, 5, 20, 60]) { t += gap * DAY; card = s.review(card, 3, t); }
    const before = card.stability!;
    t += 60 * DAY;
    card = s.review(card, 1, t);
    expect(card.stability!).toBeLessThan(before);
  });

  test("difficulty stays clamped to [1,10] under adversarial ratings", () => {
    const s = new Scheduler({ enableFuzzing: false });
    let card = newCard(START);
    let t = START;
    for (let i = 0; i < 200; i++) {
      t += (i % 5) * DAY;
      card = s.review(card, ((i % 4) + 1) as Rating, t);
      expect(card.difficulty!).toBeGreaterThanOrEqual(1);
      expect(card.difficulty!).toBeLessThanOrEqual(10);
      expect(Number.isFinite(card.stability!)).toBe(true);
      expect(card.stability!).toBeGreaterThan(0);
    }
  });

  test("all-Again never escapes learning/relearning into long intervals", () => {
    const s = new Scheduler({ enableFuzzing: false });
    let card = newCard(START);
    let t = START;
    for (let i = 0; i < 10; i++) { card = s.review(card, 1, t); t += 60_000; }
    expect(card.due - card.lastReview!).toBeLessThanOrEqual(10 * 60_000);
  });
});
